### ISSUE TITLE
link example seems confused

### ISSUE THREAD

**Issue by mcr** [core-wg/transport-indication#4]
````
  For resources discovered via CoAP's discovery interface,
  a hosting statement is typically provided by the defaults implied by {{?RFC6690}}
  where a link like `</sensor/temp>` is implied to have the relation "hosts" and the anchor `/`,
  such that a statement "coap://hostname hosts coap://hostname/sensor/temp" is implied in the link.
````
I don't understand this statement.  It feels like something is unstated, or maybe there are 6690 stuff I don't get.

**Comment by chrysn** [comment]
Link format has default values for both rel and anchor.

If a resource registers its working resource `</sensor/temp>`, and in addition a generic statement about proxying (that there is a proxy for `</>`), then all that is needed to make the connection, i.e., that `</sensors/temp>;rel=hosts;anchor="/"`, are already in place due to these defaults, and never need to be written down.

**Comment by mcr** [comment]
It's the "coap://hostname hosts coap://hostname/sensor/temp" that I'm having problems with.

**Comment by chrysn** [comment]
It doesn't have any meaning on its own, it's just something 6690 defined. It evokes all kinds of associations, but really it's just a label associating these with each other.

**Comment by chrysn** [comment]
With the "hosts" terminology removed in https://github.com/core-wg/transport-indication/pull/10, I think this can be closed.
